install.packages("DataExplorer")
if (!require(devtools)) install.packages("devtools")
devtools::install_github("boxuancui/DataExplorer", ref = "develop")
library(tidyverse)
library(DataExplorer)
Australia2$V1 <- as.factor(Australia2$V1)
Australia2$V4 <- as.factor(Australia2$V4)
Australia2$V5 <- as.factor(Australia2$V5)
Australia2$V6 <- as.factor(Australia2$V6)
Australia2$V8 <- as.factor(Australia2$V8)
Australia2$V9 <- as.factor(Australia2$V9)
Australia2$V11 <- as.factor(Australia2$V11)
Australia2$V12 <- as.factor(Australia2$V12)
Australia2$V15 <- as.factor(Australia2$V15)
glimpse(Australia)
introduce(Australia)
plot_intro(Australia)
plot_missing(Australia)
DataExplorer::plot_histogram(Australia)
DataExplorer::plot_density(Australia)
plot_correlation(Australia, cor_args = list( 'use' = 'complete.obs'))
#plot_correlation(Australia, type = 'c',cor_args = list( 'use' = 'complete.obs'))
create_report(Australia2)
